### PR TITLE
add Lescovex voting page

### PR DESCRIPTION
**Pull request by komete4**

### CODE REVIEW

**Review by komete4 — COMMENTED** [review]
add cryptaldash voting page

**Review by komete4 — COMMENTED** [review]
add exvo.io cost and submit page

**Review by cryptorex — COMMENTED** [review]
LESCOVEX has already been added...

**Review by cryptorex — CHANGES_REQUESTED** [review]
need to remove LESCOVEX and recommit without it, to merge the remainder of the changes thanks ! :)

**Review by komete4 — COMMENTED** [review]
remove lescovex

**Comment by komete4** [comment]
ready ;)

**Review by cryptorex — APPROVED** [review]

**Pull request merged**
